-- Disable RLS on all tables for hackathon simplicity
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE plan_packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_policies DISABLE ROW LEVEL SECURITY;
ALTER TABLE live_disruption_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE parametric_claims DISABLE ROW LEVEL SECURITY;
ALTER TABLE driver_activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_asset_locks DISABLE ROW LEVEL SECURITY;
ALTER TABLE coins_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE payout_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE premium_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE parametric_trigger_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE razorpay_payment_events DISABLE ROW LEVEL SECURITY;
